---
bibliography: referanser.bib 
---

# R kode {.unnumbered}

## Kapittel 2 {.unnumbered}

Sette opp nødvendige pakker:
```{r echo = TRUE, eval=FALSE}
pacman::p_load(ggplot2, readxl, tidyverse, ggpubr, dplyr, hrbrthemes)
```

Lage fig 2.1:
```{r echo = TRUE, eval=FALSE}
prepost_eksempel_long <- as_tibble(read_excel("prepost_eksempel_long.xlsx"))

ggbarplot(prepost_eksempel_long, x = "Periode", y = "Verdi", add = c("mean"), color = "blue", fill = "lightblue")
```

Lage fig 2.2:
```{r echo = TRUE, eval=FALSE}
ggline(prepost_eksempel_long, x = "Periode", y = "Verdi", add = c("mean_se", "jitter"))
```

Lage fig 2.3:
```{r echo = TRUE, eval=FALSE}
t <- 1:24

z <- c(prepost_eksempel_long$Verdi)
  
plot(t,z, type="l", col="blue", lwd=3, xlab="Periode", ylab="Antall", xaxt="n")
axis(1, seq(0,24,2))

abline(v=12, col="red", lwd = 3)
text(15.5, 40, "Endring i prosedyre", col = "red")
```

## Kapittel 3 {.unnumbered}

Lage fig 3.1:
```{r echo = TRUE, eval=FALSE}

# Genererer tilfeldig tall for regel 1:

pacman::p_load(xlsx, ggplot2, tidyverse, ggpubr)

set.seed(91)

regel1_x <- as_tibble(rnorm(100, mean = 0, sd = 1)) %>%
  rename(x = value) %>%
  add_column(nr = 1:100) %>%
  relocate(nr)

regel1_y <- as_tibble(rnorm(100, mean = 0, sd = 1)) %>%
  rename(y = value) %>%
  add_column(nr = 1:100) %>%
  relocate(nr)

regel1 <- merge(regel1_x,regel1_y,by="nr")

regel1_plot <- ggplot(regel1, aes(x = x, y = y)) +
  geom_point(size = 1) + labs(x = "x", y = "y", title = "Regel 1") + xlim(-5,5) + ylim(-5,5)+ geom_vline(xintercept = 0, col = "red") + geom_hline(yintercept = 0, col = "red")

# Genererer tilfeldig tall for regel 2:

set.seed(92)

regel2_x <- as_tibble(rnorm(100, mean = 0, sd = 2)) %>%
  rename(x = value) %>%
  add_column(nr = 1:100) %>%
  relocate(nr)

## Setter sd = 2 fordi variasjonen med regel 2 er dobbel av regel 1 (jfr SPC for Excel)

regel2_y <- as_tibble(rnorm(100, mean = 0, sd = 2)) %>%
  rename(y = value) %>%
  add_column(nr = 1:100) %>%
  relocate(nr)

regel2 <- merge(regel2_x,regel2_y,by="nr")

regel2_plot <- ggplot(regel2, aes(x = x, y = y)) +
  geom_point(size = 1) + labs(x = "x", y = "y", title = "Regel 2") + xlim(-5,5) + ylim(-5,5) + geom_vline(xintercept = 0, col = "red") + geom_hline(yintercept = 0, col = "red")

# Henter tall fra Excel for regel 3:

regel3 <- read.xlsx("Funnel_blankedata_regel3.xlsx", 1)

regel3_plot <- ggplot(regel3, aes(x = Regel_3_x, y = Regel_3_y)) +
  geom_point(size = 1) + labs(x = "x", y = "y", title = "Regel 3") + xlim(-5,5) + ylim(-5,5)+ geom_vline(xintercept = 0, col = "red") + geom_hline(yintercept = 0, col = "red")

# Henter tall fra Excel for regel 4:

regel4 <- read.xlsx("Funnel_blankedata_regel4.xlsx", 1)

regel4_plot <- ggplot(regel4, aes(x = Regel_4_x, y = Regel_4_y)) +
  geom_point(size = 1) + labs(x = "x", y = "y", title = "Regel 4") + xlim(-5,5) + ylim(-5,5)+ geom_vline(xintercept = 0, col = "red") + geom_hline(yintercept = 0, col = "red")

# Setter plottene sammen:

ggarrange(regel1_plot, regel2_plot, regel3_plot, regel4_plot 
 + rremove("x.text"), ncol = 2, nrow = 2)

```

Lage fig 3.2:
```{r echo = TRUE, eval=FALSE}

regel3_2 <- read.xlsx("Funnel_blankedata_regel3_2.xlsx", 1)

regel3_2_plot <- ggplot(regel3_2, aes(x = x, y = y)) +
  geom_point(size = 1) + labs(x = "x", y = "y", title = "Regel 3 - annet førstetreff") + xlim(-5,5) + ylim(-5,5)+ geom_vline(xintercept = 0, col = "red") + geom_hline(yintercept = 0, col = "red")

regel3_2_plot 

```

Lage fig 3.3:

```{r echo = TRUE, eval=FALSE}

regel4_2 <- read.xlsx("Funnel_blankedata_regel4_2.xlsx", 1)

regel4_2_plot <- ggplot(regel4_2, aes(x = x, y = y)) +
  geom_point(size = 1) + labs(x = "x", y = "y", title = "Regel 4 - annet førstetreff") + xlim(-2,10) + ylim(-10,2)+ geom_vline(xintercept = 0, col = "red") + geom_hline(yintercept = 0, col = "red")

regel4_2_plot
```

Lage fig 3.4:

```{r echo = TRUE, eval=FALSE}

pacman::p_load(qicharts2)

regel1x <- regel1 %>% pull(2)

regel1y <- regel1 %>% pull(3)

regel1xrun <- qic(regel1x, title = 'x-verdi ved regel 1', ylab = "verdi", xlab = "Forsøk nr.")

regel1yrun <- qic(regel1y, title = 'y-verdi ved regel 1', ylab = "verdi", xlab = "Forsøk nr.")

ggarrange(regel1xrun, regel1yrun + rremove("x.text"), ncol = 2, nrow = 1,  widths = c(1, 1))

```

Lage fig 3.5:

```{r echo = TRUE, eval=FALSE}

pacman::p_load(qicharts2)

regel2x <- regel2 %>% pull(2)

regel2y <- regel2 %>% pull(3)

regel2xrun <- qic(regel2x, title = 'x-verdi ved regel 2', ylab = "verdi", xlab = "Forsøk nr.")

regel2yrun <- qic(regel2y, title = 'y-verdi ved regel 2', ylab = "verdi", xlab = "Forsøk nr.")

ggarrange(regel2xrun, regel2yrun + rremove("x.text"), ncol = 2, nrow = 1,  widths = c(1, 1))

```

Lage fig 3.6:

```{r echo = TRUE, eval=FALSE}

pacman::p_load(qicharts2)

regel3x <- regel3 %>% pull(2)

regel3y <- regel3 %>% pull(3)

regel3xrun <- qic(regel3x, title = 'x-verdi ved regel 3', ylab = "verdi", xlab = "Forsøk nr.")

regel3yrun <- qic(regel3y, title = 'y-verdi ved regel 3', ylab = "verdi", xlab = "Forsøk nr.")

ggarrange(regel3xrun, regel3yrun + rremove("x.text"), ncol = 2, nrow = 1,  widths = c(1, 1))

```

Lage fig 3.7:

```{r echo = TRUE, eval=FALSE}

pacman::p_load(qicharts2)

regel4x <- regel4 %>% pull(2)

regel4y <- regel4 %>% pull(3)

regel4xrun <- qic(regel4x, title = 'x-verdi ved regel 4', ylab = "verdi", xlab = "Forsøk nr.")

regel4yrun <- qic(regel4y, title = 'y-verdi ved regel 4', ylab = "verdi", xlab = "Forsøk nr.")

ggarrange(regel4xrun, regel4yrun + rremove("x.text"), ncol = 2, nrow = 1,  widths = c(2, 2))

```

Lage fig 3.8:

```{r echo = TRUE, eval=FALSE}

pacman::p_load(xlsx, qicharts2, tidyverse, ggplot2, ggpubr)

toteam1 <- read.xlsx("toteam.xlsx", 1)

team1 <- qic(Team.1,
    data      = toteam1, 
    chart     = 'i',
    show.grid = TRUE,
    title     = "Team 1",
    ylab      = "Antall defekter pr uke",
    xlab      = "Uke #")

team2 <- qic(Team.2,
    data      = toteam1, 
    chart     = 'i',
    show.grid = TRUE,
    title     = "Team 2",
    ylab      = "Antall defekter pr uke",
    xlab      = "Uke #")

ggarrange(team1, team2 + rremove("x.text"), ncol = 2, nrow = 1,  widths = c(1, 1))
```

Lage fig 3.9:

```{r echo = TRUE, eval=FALSE}

pacman::p_load(xlsx, qicharts2, tidyverse, ggplot2, ggpubr)

toteam2 <- readxl::read_excel("toteam.xlsx") %>%
  pivot_longer(c("Team 1", "Team 2"))

qic(Nr, value,
    data = toteam2,
    facets = ~name,
    xlab = "Uke #",
    ylab = "Antall defekter pr uke",
    title = "To team - like prosesser - ulik variasjon")
```
